docker:
  image: yegor256/rultor
assets:
  settings.xml: "portlek/secret-repo#general/settings.xml"
  pubring.gpg: "portlek/secret-repo#general/pubring.gpg"
  secring.gpg: "portlek/secret-repo#general/secring.gpg"
architect:
  - portlek
merge:
  script:
    - mvn clean dokka:javadocJar install --errors --settings /home/r/settings.xml
deploy:
  script:
    - mvn clean dokka:javadocJar deploy --errors --settings /home/r/settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" --settings /home/r/settings.xml
    mvn clean dokka:javadocJar deploy --errors --settings /home/r/settings.xml